apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    name: server
spec:
  containers:
  - name: server
    image: kadu123/server
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081


